exclude: |
    (?x)(
        ^packages/arb-avm-cpp/external/keccak/|
        ^packages/arb-bridge-eth/installed_contracts/
    )
repos:
    - repo: https://github.com/psf/black
      rev: stable
      hooks:
          - id: black
            language_version: python3.6
    - repo: git://github.com/doublify/pre-commit-clang-format
      rev: master

      hooks:
          - id: clang-format
    - repo: git://github.com/dnephin/pre-commit-golang
      rev: master
      hooks:
          - id: go-fmt
    - repo: https://github.com/prettier/prettier
      rev: "" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
          - id: flake8
