coverage:
  status:
    project:
      default: off
      build:
        flags: [unit, integration]

flags: unit
  integration

ignore:
  - 'packages/arb-validator-core/ethbridge/arbfactory/*'
  - 'packages/arb-validator-core/ethbridge/challengefactory/*'
  - 'packages/arb-validator-core/ethbridge/globalinbox/*'
  - 'packages/arb-validator-core/ethbridge/executionchallenge/*'
  - 'packages/arb-validator-core/ethbridge/messageschallenge/*'
  - 'packages/arb-validator-core/ethbridge/inboxtopchallenge/*'
  - 'packages/arb-validator-core/ethbridge/challengetester/*'
  - 'packages/arb-validator-core/ethbridge/messagetester/*'
  - 'packages/arb-validator-core/ethbridge/sigutilstester/*'
  - 'packages/arb-validator-core/ethbridge/rollup/*'
  - 'tests/fibgo/fibabi.go'
  - 'packages/arb-provider-ethers/src/lib/abi/*'
  - '**/*.pb.go'
