coverage:
  status:
    project:
      default: off
      unit:
        flags:
          - unit
      integration:
        flags:
          - integration

flags:
  unit: {}
  integration: {}

ignore:
  - 'packages/arb-validator-core/ethbridge/arbfactory'
  - 'packages/arb-validator-core/ethbridge/challengefactory'
  - 'packages/arb-validator-core/ethbridge/globalinbox'
  - 'packages/arb-validator-core/ethbridge/executionchallenge'
  - 'packages/arb-validator-core/ethbridge/messageschallenge'
  - 'packages/arb-validator-core/ethbridge/inboxtopchallenge'
  - 'packages/arb-validator-core/ethbridgetest'
  - 'packages/arb-validator-core/ethbridge/rollup'
  - 'packages/arb-validator/proofmachine/machinetester'
  - 'packages/arb-provider-go/arbsys.go'
  - 'packages/arb-provider-go/arbinfo.go'
  - 'packages/arb-avm-cpp/external/keccak'
  - 'tests/fibgo/fibabi.go'
  - 'packages/arb-provider-ethers/src/lib/abi'
  - '**/*.pb.go'
