[rpc]
port = 7545
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "pubsub", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[websockets]
disable = false
port = 7546
interface = "all"
apis = ["web3", "eth", "net", "parity", "pubsub", "traces", "rpc", "secretstore"]
hosts = ["all"]

[mining]
engine_signer = "0xe83f8ae25F873b1e17e05bda065ABEAc2FbD2E82"
min_gas_price = 1
# Targeting 7500000 gas per block when sealing a new block.
gas_floor_target = "7500000"
# Gas limit will be raised at most by 7500000 gas.
gas_cap = "7500000"
# Parity will reject transactions above 7500000 gas.
tx_gas_limit = "7500000"
