version: 2
jobs:
  build:
    docker:
      - image: offchainlabs/build-base:0.1.2
    working_directory: /home/user/arbitrum
    steps:
      - run:
          name: Setup enviroment
          command: |
            mv /home/user/arbitrum/vconan/ /home/user/vconan/
            curl -s https://codecov.io/bash > ../codecovbash
            chmod +x ../codecovbash
      - checkout

      - restore_cache:
          keys:
            - go-mod-v2-{{ .Branch }}-{{ checksum "packages/arb-validator/go.sum" }}
            - go-mod-v2-{{ .Branch }}-
            - go-mod-v2-
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - restore_cache:
          keys:
            - conan-packages-v1-{{ .Branch }}-{{ checksum "packages/arb-avm-cpp/conanfile.txt" }}
            - conan-packages-v1-{{ .Branch }}-
            - conan-packages-v1-
      - restore_cache:
          keys:
            - python-packages-v1-{{ .Branch }}-{{ checksum "packages/arb-compiler-evm/requirements.txt" }}
            - python-packages-v1-{{ .Branch }}-
            - python-packages-v1-
      - run:
          name: build all
          command: |
            mv /home/user/vconan/ /home/user/arbitrum/vconan/
            mv ../codecovbash codecovbash
            yarn install --cache-folder ~/.cache/yarn
            yarn 'install:validator'
            yarn 'install:ci'
      - save_cache:
          key: go-mod-v2-{{ checksum "packages/arb-validator/go.sum" }}
          paths:
            - ~/go/pkg/mod
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - ~/.conan/data
          key: conan-packages-v1-{{ .Branch }}-{{ checksum "packages/arb-avm-cpp/conanfile.txt" }}
      - save_cache:
          paths:
            - ~/.local/lib/python3.7/site-packages
          key: python-packages-v1-{{ .Branch }}-{{ checksum "packages/arb-compiler-evm/requirements.txt" }}
      - run:
          name: test arb-avm-cpp
          command: |
            ctest .
            lcov --capture --directory . --output-file coverage.info
            lcov --remove coverage.info --output-file coverage.info '*/.conan/*' '/usr/*' '*/tests/*' '*/external/*'
            lcov --list coverage.info
            ../../../codecovbash -R /home/user/arbitrum -f coverage.info -cF arb_avm_cpp
            cd .. && rm -rf ci
          working_directory: /home/user/arbitrum/packages/arb-avm-cpp/ci
      - run:
          name: test arb-avm-go
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic ./...
            ../../codecovbash -R /home/user/arbitrum -cF arb_avm_go
          working_directory: /home/user/arbitrum/packages/arb-avm-go
      - run:
          name: test arb-bridge-eth
          command: |
            ganache-cli -p 7545 &
            truffle migrate --reset --compile-all
            kill $!
            ../../codecovbash -R /home/user/arbitrum -cF arb_bridge_eth
          working_directory: /home/user/arbitrum/packages/arb-bridge-eth
      - run:
          name: test arb-compiler-evm
          command: |
            coverage run --source=arbitrum/ setup.py test
            cd tests/sol-syscall
            truffle migrate --reset --compile-all --network arbitrum
            coverage run --source=../../arbitrum/ truffle_runner.py compiled.json
            cd ../..
            coverage combine .coverage tests/sol-syscall/.coverage
            ../../codecovbash -R /home/user/arbitrum -cF arb_compiler_evm
          working_directory: /home/user/arbitrum/packages/arb-compiler-evm
      - run:
          name: test arb-provider-ethers
          command: |
            yarn jest --coverage
            ../../codecovbash -R /home/user/arbitrum -cF arb_provider_ethers
          working_directory: /home/user/arbitrum/packages/arb-provider-ethers
      - run:
          name: test arb-provider-go
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic ./...
            ../../codecovbash -R /home/user/arbitrum -cF arb_provider_go
          working_directory: /home/user/arbitrum/packages/arb-provider-go
      - run:
          name: test arb-provider-truffle
          command: |
            yarn jest --coverage --pass-with-no-tests
            ../../codecovbash -R /home/user/arbitrum -cF arb_provider_truffle
          working_directory: /home/user/arbitrum/packages/arb-provider-truffle
      - run:
          name: test arb-provider-web3
          command: |
            yarn jest --coverage --pass-with-no-tests
            ../../codecovbash -R /home/user/arbitrum -cF arb_provider_web3
          working_directory: /home/user/arbitrum/packages/arb-provider-web3
      - run:
          name: test arb-util
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic ./...
            ../../codecovbash -R /home/user/arbitrum -cF arb_util
          working_directory: /home/user/arbitrum/packages/arb-util
      - run:
          name: test arb-validator
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic ./...
            ../../codecovbash -R /home/user/arbitrum -cF arb_validator
          working_directory: /home/user/arbitrum/packages/arb-validator
