name: Build and test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-unit:
    name: Test storage layout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup node/yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build

      - name: Test Storage Layouts
        run: yarn run test:storage
  test-token-bridge-deployer:
    name: Test hardhat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup node/yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install packages
        run: yarn

      - name: Compile contracts
        run: yarn build

      - name: Deploy token bridge
        run: yarn run deploy:tokenbridge:atomic

      - name: Test token bridge deployment
        run: yarn run test:tokenbridge:deployment